### ISSUE TITLE
Dates in "stats over time" are wrong

### ISSUE THREAD

**Issue by augusto-herrmann** [DataShades/datashades-info#1]
On any page with stats about CKAN portals, [like this one](https://datashades.info/portal/http%3A%2F%2Fdados.gov.br%2F), the x-axis, that should display a date, gets completely crazy numbers ranging from 1400 to 3200. Example screenshot below.

![datashades-dates](https://user-images.githubusercontent.com/1058414/113030464-01546f80-9164-11eb-9a32-189272a48cf3.png)

**Comment by AlekseyPavlyuk** [comment]
> On any page with stats about CKAN portals, [like this one](https://datashades.info/portal/http%3A%2F%2Fdados.gov.br%2F), the x-axis, that should display a date, gets completely crazy numbers ranging from 1400 to 3200. Example screenshot below.
Thanks for your feedback we will fix it soon

**Comment by augusto-herrmann** [comment]
Hi @AlekseyPavlyuk,

the problem with the dates is still there.

![datashades-dates](https://user-images.githubusercontent.com/1058414/139445652-b85872d2-d379-4342-8181-806455cb98a9.gif)

**Comment by Alex-Pavlyuk** [comment]
@augusto-herrmann thanks Augusto, I think we just overrode the fix. We will apply it again soon.

**Comment by Alex-Pavlyuk** [comment]
@augusto-herrmann fixed

**Comment by augusto-herrmann** [comment]
@AlekseyPavlyuk thanks!
